version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: sale_management_db
    restart: always
    environment:
      MYSQL_DATABASE: sale_management
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: htquanlybanhang_app
    restart: always
    ports:
      - "6699:6699"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sale_management?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root123
      - SERVER_PORT=6699
    depends_on:
      - db

volumes:
  mysql_data: