
spring.application.name=HTQUANLYBANHANG

# ==================================================
# DATABASE MYSQL
# ==================================================

spring.datasource.url=jdbc:mysql://localhost:3306/sale_management?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==================================================
# JPA / HIBERNATE
# ==================================================

# Chỉ kiểm tra Entity có khớp Database hay không
spring.jpa.hibernate.ddl-auto=validate

# Hiển thị SQL trong Console khi debug
spring.jpa.show-sql=true


# Format SQL cho dễ đọc
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# ==================================================
# SERVER
# ==================================================

server.port=6699

